#!/usr/bin/env python3
"""
gen_listings.py - regenerate the annotated disassembly listings for the
subsystems documented in docs/ (mapper, randomizer, NPC AI, text codec).

Output goes to build/listings/ which is git-ignored: the listings are
ROM-derived (copyrighted code) and are treated as a *generated* artifact,
exactly like the ROM itself. Run this against your own legally-dumped
ROM to materialise the human-readable disassembly locally.

    python tools/gen_listings.py "path/to/your.nes"

The symbol file src/jeopardy.sym.json (labels/comments/data ranges that
were authored here, not copied from the ROM) supplies the annotations.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from disasm6502 import Rom, Symbols, listing, trace, BANK  # noqa: E402

# (bank, start, end, title) — the regions reverse-engineered in docs/.
REGIONS = [
    (0, 0xFF80, 0xFFFA, "AOROM far-call trampoline + RESET + delay thunk (mapper.md)"),
    (0, 0x8000, 0x80E0, "Dispatcher + cold boot (mapper.md)"),
    (1, 0x8000, 0x8040, "Bank-1 cross-bank jump table (mapper.md)"),
    (0, 0x91F2, 0x925A, "PPU/OAM init + UI string writers (text-format.md)"),
    (0, 0x92BE, 0x93B0, "Bank-0 vblank NMI + palette flush (mapper.md)"),
    (0, 0x9116, 0x913A, "Palette upload loop (research-notes.md)"),
    (0, 0x82B1, 0x835D, "Gameboard random bag: fill + draw (randomizer.md)"),
    (0, 0x9027, 0x904A, "RNG 'stir the pot' generator (randomizer.md)"),
    (0, 0x8DA2, 0x8E00, "Board-cursor state handler -> difficulty $9B (npc-ai.md)"),
    (0, 0x8E5C, 0x8ED0, "CPU name picker, re-roll on collision (npc-ai.md)"),
    (0, 0x8F0C, 0x8F23, "CPU face/attribute picker (npc-ai.md)"),
    (0, 0xA7F2, 0xA80D, "CPU reaction-time roll (npc-ai.md)"),
    (0, 0x9733, 0x97AC, "Per-frame buzz poll / countdown (npc-ai.md)"),
    (0, 0x9A7F, 0x9AB5, "Daily Double placement (npc-ai.md)"),
]

HW_VECTORS = "; vectors live in the bank tail $FFFA-$FFFF (see mapper.md)\n"


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gen_listings.py <rom.nes>")
    rom = Rom(sys.argv[1])
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    syms = Symbols(os.path.join(here, "src", "jeopardy.sym.json"))
    outdir = os.path.join(here, "build", "listings")
    os.makedirs(outdir, exist_ok=True)

    combined = []
    for bank, start, end, title in REGIONS:
        body = listing(rom, bank, start, end, syms)
        block = ("; ============================================================\n"
                 "; bank %d  $%04X-$%04X  %s\n"
                 "; ============================================================\n%s\n"
                 % (bank, start, end, title, body))
        combined.append(block)

    path = os.path.join(outdir, "documented.lst")
    with open(path, "w") as f:
        f.write("; Jeopardy! 25th Anniversary (NES) - annotated disassembly\n")
        f.write("; Generated by tools/gen_listings.py from your ROM. Do not commit\n")
        f.write("; (ROM-derived). Analysis: see docs/.\n\n")
        f.write("\n".join(combined))
    print("wrote", path, "(%d regions)" % len(REGIONS))


if __name__ == "__main__":
    main()
